### ISSUE TITLE
Bug in environment creation

### ISSUE THREAD

**Issue by mertalbaba** [qxcv/magical#4]
I am trying to train a model in one of your environments on a server. When I call `env = gym.make('MoveToCorner-Demo-v0')`, I get the following error `pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"`

All classic gym environments works well on the server, so the problem is related to Magical environments. How can I solve this?

**Comment by qxcv** [comment]
You need an X server.  Try running the script with `xvfb-run -a` (e.g. `xvfb-run -a python name_of_your_script.py`).

**Comment by mertalbaba** [comment]
Thanks!
